/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import SQL.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author xandros
 */
public class NewLessonPopup extends javax.swing.JFrame {

    /**
     * Creates new form Notifications
     */
    

    public NewLessonPopup() {
        initComponents();
    }

    String url = "jdbc:postgresql://localhost:5432/chat_app";
    String user = "postgres";
    String dpassword = "ahmad";

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        LessonNameField = new javax.swing.JTextField();
        LessonNoField = new javax.swing.JTextField();
        LessonDepartmentField = new javax.swing.JTextField();
        LessonTotalKontField = new javax.swing.JTextField();
        LessonTeacherNoField = new javax.swing.JTextField();
        OlusturButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.POPUP);

        Panel.setBackground(new java.awt.Color(34, 40, 44));
        Panel.setToolTipText("");
        Panel.setPreferredSize(new java.awt.Dimension(1000, 100));

        LessonNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LessonNameField.setText("Ders Adi");
        LessonNameField.setPreferredSize(new java.awt.Dimension(300, 22));
        LessonNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonNameFieldActionPerformed(evt);
            }
        });

        LessonNoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LessonNoField.setText("Ders No");
        LessonNoField.setPreferredSize(new java.awt.Dimension(300, 22));
        LessonNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonNoFieldActionPerformed(evt);
            }
        });

        LessonDepartmentField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LessonDepartmentField.setText("ilgi alanlar");
        LessonDepartmentField.setPreferredSize(new java.awt.Dimension(300, 22));
        LessonDepartmentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonDepartmentFieldActionPerformed(evt);
            }
        });

        LessonTotalKontField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LessonTotalKontField.setText("Kontenjan");
        LessonTotalKontField.setPreferredSize(new java.awt.Dimension(300, 22));
        LessonTotalKontField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonTotalKontFieldActionPerformed(evt);
            }
        });

        LessonTeacherNoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LessonTeacherNoField.setText("Hoca Sicil Numarasi");
        LessonTeacherNoField.setPreferredSize(new java.awt.Dimension(300, 22));
        LessonTeacherNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonTeacherNoFieldActionPerformed(evt);
            }
        });

        OlusturButton.setBackground(new java.awt.Color(0, 102, 102));
        OlusturButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        OlusturButton.setForeground(new java.awt.Color(255, 255, 255));
        OlusturButton.setText("Ders Olustur");
        OlusturButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlusturButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LessonTeacherNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(LessonNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OlusturButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(LessonNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LessonDepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LessonTotalKontField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LessonNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LessonNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LessonDepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LessonTotalKontField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LessonTeacherNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(OlusturButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(766, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LessonNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LessonNameFieldActionPerformed

    private void LessonNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LessonNoFieldActionPerformed

    private void LessonDepartmentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonDepartmentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LessonDepartmentFieldActionPerformed

    private void LessonTotalKontFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonTotalKontFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LessonTotalKontFieldActionPerformed

    private void LessonTeacherNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonTeacherNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LessonTeacherNoFieldActionPerformed

    private void OlusturButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlusturButtonActionPerformed
        // TODO add your handling code here:
        LessonOperation lessonOperation = new LessonOperation();
        lessonOperation.createLesson(LessonNameField.getText(), LessonNoField.getText(),
                LessonDepartmentField.getText(), Integer.parseInt(LessonTotalKontField.getText()),
                Integer.parseInt(LessonTeacherNoField.getText()));
        this.dispose();
    }//GEN-LAST:event_OlusturButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLessonPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLessonPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLessonPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLessonPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLessonPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LessonDepartmentField;
    private javax.swing.JTextField LessonNameField;
    private javax.swing.JTextField LessonNoField;
    private javax.swing.JTextField LessonTeacherNoField;
    private javax.swing.JTextField LessonTotalKontField;
    private javax.swing.JButton OlusturButton;
    private javax.swing.JPanel Panel;
    // End of variables declaration//GEN-END:variables
}
