/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import SQL.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

/**
 *
 * @author xandros
 */
public class StudentUpdate extends javax.swing.JFrame {

    /**
     * Creates new form Notifications
     */
    TablesOperation tableReader = new TablesOperation();
    
    public StudentUpdate(Student student) {
        initComponents();
        StudentNameField.setText(student.getStudentName());
        StudentNoLabel.setText(Integer.toString(student.getStudentNo()));
        StudentDepartmentField.setText(student.getIlgiAlanlar());
        StudentAgnoField.setText(Double.toString(student.getAcademicAverage()));
        
    }

    public StudentUpdate() {
    }


    String url = "jdbc:postgresql://localhost:5432/chat_app";
    String user = "postgres";
    String dpassword = "ahmad";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        StudentNameField = new javax.swing.JTextField();
        StudentPasswordField = new javax.swing.JTextField();
        CreateStudentWithPassword = new javax.swing.JButton();
        StudentDepartmentField = new javax.swing.JTextField();
        StudentAgnoField = new javax.swing.JTextField();
        CreateStudentWithoutPassword = new javax.swing.JButton();
        StudentNoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.POPUP);

        Panel.setBackground(new java.awt.Color(34, 40, 44));
        Panel.setToolTipText("");
        Panel.setPreferredSize(new java.awt.Dimension(1000, 100));

        StudentNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StudentNameField.setText("Ad-Soyad");
        StudentNameField.setPreferredSize(new java.awt.Dimension(300, 22));
        StudentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNameFieldActionPerformed(evt);
            }
        });

        StudentPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StudentPasswordField.setText("Sifre");
        StudentPasswordField.setPreferredSize(new java.awt.Dimension(300, 22));
        StudentPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPasswordFieldActionPerformed(evt);
            }
        });

        CreateStudentWithPassword.setBackground(new java.awt.Color(0, 51, 102));
        CreateStudentWithPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateStudentWithPassword.setText("Sifre ile Guncelleme");
        CreateStudentWithPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateStudentWithPasswordActionPerformed(evt);
            }
        });

        StudentDepartmentField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StudentDepartmentField.setText("Bolum");
        StudentDepartmentField.setPreferredSize(new java.awt.Dimension(300, 22));
        StudentDepartmentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentDepartmentFieldActionPerformed(evt);
            }
        });

        StudentAgnoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StudentAgnoField.setText("AGNO");
        StudentAgnoField.setPreferredSize(new java.awt.Dimension(300, 22));
        StudentAgnoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentAgnoFieldActionPerformed(evt);
            }
        });

        CreateStudentWithoutPassword.setBackground(new java.awt.Color(51, 51, 0));
        CreateStudentWithoutPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateStudentWithoutPassword.setText("Sifresiz Guncelleme");
        CreateStudentWithoutPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateStudentWithoutPasswordActionPerformed(evt);
            }
        });

        StudentNoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StudentNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        StudentNoLabel.setText("Ogrenci No");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(StudentNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StudentAgnoField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(StudentDepartmentField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(StudentPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(StudentNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(CreateStudentWithPassword))))
                        .addGap(18, 18, 18)
                        .addComponent(CreateStudentWithoutPassword)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(StudentNoLabel)
                .addGap(18, 18, 18)
                .addComponent(StudentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StudentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StudentDepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StudentAgnoField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateStudentWithPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateStudentWithoutPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(766, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StudentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNameFieldActionPerformed

    private void StudentPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentPasswordFieldActionPerformed

    private void CreateStudentWithPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateStudentWithPasswordActionPerformed
        // TODO add your handling code here:
        tableReader.updateStudentWithPassword(Integer.parseInt(StudentNoLabel.getText()), StudentNameField.getText(),
                StudentPasswordField.getText(), StudentDepartmentField.getText(), Double.parseDouble(StudentAgnoField.getText()));
        this.dispose();
    }//GEN-LAST:event_CreateStudentWithPasswordActionPerformed

    private void StudentDepartmentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentDepartmentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentDepartmentFieldActionPerformed

    private void StudentAgnoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentAgnoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentAgnoFieldActionPerformed

    private void CreateStudentWithoutPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateStudentWithoutPasswordActionPerformed
        // TODO add your handling code here:
        tableReader.updateStudentWithOutPassword(Integer.parseInt(StudentNoLabel.getText()), StudentNameField.getText()
                , StudentDepartmentField.getText(), Double.parseDouble(StudentAgnoField.getText()));
        this.dispose();
    }//GEN-LAST:event_CreateStudentWithoutPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateStudentWithPassword;
    private javax.swing.JButton CreateStudentWithoutPassword;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField StudentAgnoField;
    private javax.swing.JTextField StudentDepartmentField;
    private javax.swing.JTextField StudentNameField;
    private javax.swing.JLabel StudentNoLabel;
    private javax.swing.JTextField StudentPasswordField;
    // End of variables declaration//GEN-END:variables
}
